### PR TITLE
Adding a DART trigger catalogue to the repo

### PR DESCRIPTION
**Pull request by meganmadley**
Please don't merge

### CODE REVIEW

**Review by JonoHanson — COMMENTED** [review]
can you clarify if these are auto or manual triggers or both in th read_me, please.

**Comment by meganmadley** [comment]
@JonoHanson added `automatic` to both readme. We can add the manual ones in the future if we would like?

**Comment by salichon** [comment]
Hello! @meganmadley 
Would you think it has value deal with the manual "Operational triggers" for enhanced monitoring"  Vs the "Test triggers" while checking the operational status of P or S channels of a system?

**Comment by meganmadley** [comment]
Thanks @salichon, I could add the operational manual triggers that show something? It would definitely bulk out the catalogue. This would also not be all of the triggers because for Tonga quite a few of the DARTs were getting manually triggered every few hours. Although, once you have the initial trigger time then you can see the following triggers quite easily (if you're looking at the signals in TILDE Data Discovery), so there would only really be value in adding the manual operational ones, if they are on a different DART to the automatic trigger and then possibly only the first one

**Comment by salichon** [comment]
Now :) - i see that this catalogue is entitled with "automatic" triggers which have some scientific value :)  
I agree - these "operational manual" are not relevant as  observations and would make noise.
So if manual switches ever came to be listed these would a be a different list.

**Comment by meganmadley** [comment]
Sounds good, I think we could look at adding manual triggers in the future, but for now, just have the automatic ones

**Review by JonoHanson — APPROVED** [review]
all good for now, lets publish automatic only and look at adding manual in the near future

@salichon can we get a review from you, too, please

**Review by salichon — COMMENTED** [review]
Helo @meganmadley  @JonoHanson 
Is there any references about that classification  (methods and Author) ?

Note that to my knowledge having such a catalogue seems to be quite unique - or equivalent at least not referenced or easily available. 
The only reference i found is "https://ui.adsabs.harvard.edu/abs/2007AGUFM.S53A1027B/abstract" which leads to ... nowhere. or at least  fell short.

I reckon  the publication of such a higher level data sets for NZ is worth a publication/Notification  somewhere,  (provided a solid classification method).

Cheers

**Review by salichon — COMMENTED** [review]
or at least a mention that
the "automatic triggers have been reviewed at GNS  by a speciailist. The triggers were  classified and reviewed  with regards to their expertise....  or something similar 
For more information contact Geonet/help etc ...

**Review by salichon — APPROVED** [review]

**Pull request merged**
